// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kr3jyTtEhGZFU8wxFE4fvF-ZIrXvZF8',
    appId: '1:20863115030:web:2f670025d86ea3cd1d3a37',
    messagingSenderId: '20863115030',
    projectId: 'chat-app-44bca',
    authDomain: 'chat-app-44bca.firebaseapp.com',
    storageBucket: 'chat-app-44bca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8IWxRAyuFftsH0_cuPpnyGdx0Rtehbss',
    appId: '1:20863115030:android:f594bc4ce01d64b81d3a37',
    messagingSenderId: '20863115030',
    projectId: 'chat-app-44bca',
    storageBucket: 'chat-app-44bca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmc8ve0_i7iO7tFio09cwHt-ve0baq20',
    appId: '1:20863115030:ios:1f267d87d3702eb91d3a37',
    messagingSenderId: '20863115030',
    projectId: 'chat-app-44bca',
    storageBucket: 'chat-app-44bca.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmc8ve0_i7iO7tFio09cwHt-ve0baq20',
    appId: '1:20863115030:ios:1f267d87d3702eb91d3a37',
    messagingSenderId: '20863115030',
    projectId: 'chat-app-44bca',
    storageBucket: 'chat-app-44bca.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kr3jyTtEhGZFU8wxFE4fvF-ZIrXvZF8',
    appId: '1:20863115030:web:e3f1034d3118ad8c1d3a37',
    messagingSenderId: '20863115030',
    projectId: 'chat-app-44bca',
    authDomain: 'chat-app-44bca.firebaseapp.com',
    storageBucket: 'chat-app-44bca.appspot.com',
  );
}
